create database jwtsecurity_db;

use jwtsecurity_db;

CREATE TABLE USER_TBL (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
    #created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

CREATE TABLE ROLE_TBL (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
)  ENGINE=INNODB;
